"""GLEIPNIR round renderer — the ONLY source of Caliper benchconfigs and network
configs, rendered from benchmark/sweeps.yaml (docs/CONTRACTS.md §10, §11;
supervisor brief 2026-09-22 §9). A library, no CLI: experiment.py renders every
config per run into the run dir (nothing generated is committed).

Library use (experiment.py): `render_round(...)` returns one benchconfig dict
(one round + the docker resource monitor block); `network_config(variant, C)`
picks the network config and `render_parallel_network(C)` renders the parallel
one; `smoke_rounds` / `ops_rounds` / `trace_round` build round specs.
Round-argument NAMES are binding (brief §4): the workloads read
`mode`, `label`, `channels`, `trace`, `slice`, `sliceSize`, `variant`, `pool`,
`payloadBytes`, `fn`, `seedCount`.

Container names in the monitor block MUST keep the leading slash: Caliper 0.6.0
matches `Names[0]` of `docker.listContainers()` verbatim (monitor-docker.js).
"""
import os

import yaml

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BENCH_DIR = os.path.join(REPO_ROOT, "benchmark")
SWEEPS_PATH = os.path.join(BENCH_DIR, "sweeps.yaml")

VARIANTS = ["standard", "anchoring", "parallel", "parallel-anchored"]
REST_VARIANTS = ("anchoring", "parallel-anchored")      # write path = gateway BFF (rest connector)
ANCHORED_VARIANTS = REST_VARIANTS
MULTI_CHANNEL_VARIANTS = ("parallel", "parallel-anchored")

GENERATED = "# GENERATED by orchestration/rounds.py from benchmark/sweeps.yaml — do not edit by hand."

# Docker container names per variant (leading slash = Caliper's Names[0] form).
_BASE_CONTAINERS = [
    "/orderer0.example.com", "/orderer1.example.com", "/orderer2.example.com",
    "/peer0.org1.example.com", "/peer0.org2.example.com",
    "/ccaas-evidence", "/gleipnir-gateway",
]
_ANCHORING_CONTAINERS = ["/gleipnir-merkle-batcher", "/gleipnir-receipt-store", "/gleipnir-verification"]
_PARALLEL_ANCHORED_CONTAINERS = ["/peer0.anchor.example.com", "/ccaas-evidence-anchor", "/gleipnir-anchor-client"]

# The identity/connection-profile block of networks/coc-main.yaml, copied verbatim.
_ORG1_IDENTITY_BLOCK = """organizations:
  - mspid: Org1MSP
    identities:
      certificates:
        - name: User1
          clientPrivateKey:
            path: ../network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/priv_sk
          clientSignedCert:
            path: ../network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/cert.pem
    connectionProfile:
      path: networks/connection-org1.yaml
      discover: false
"""


def load_sweeps(path=SWEEPS_PATH):
    with open(path, encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def mode_for(variant):
    return "rest" if variant in REST_VARIANTS else "fabric"


def channels_for(variant, channels):
    """Code-enforced: Standard and Anchoring are single-channel (brief §1 Q2)."""
    return int(channels) if variant in MULTI_CHANNEL_VARIANTS else 1


def monitor_containers(variant):
    names = list(_BASE_CONTAINERS)
    if variant in ANCHORED_VARIANTS:
        names += _ANCHORING_CONTAINERS
    if variant == "parallel-anchored":
        names += _PARALLEL_ANCHORED_CONTAINERS
    return names


def network_config(variant, channels=1):
    """Relative to the Caliper workspace (benchmark/); parallel-c{C}.yaml is not committed —
    experiment.py writes render_parallel_network(C) under that name into the run dir."""
    if variant == "standard":
        return "networks/coc-main.yaml"
    if variant == "parallel":
        return f"networks/parallel-c{channels_for(variant, channels)}.yaml"
    return "networks/rest-gateway.yaml"


def case_name(n):
    return f"case-{n:03d}"


# ---------------------------------------------------------------- round specs
# A round spec is {label, module, txNumber, sendRateTps, arguments}; the common
# arguments (mode/label/channels) are added by render_bench.

def _spec(label, module, tx_number, send_rate_tps, arguments=None):
    return {"label": label, "module": f"workload/{module}", "txNumber": int(tx_number),
            "sendRateTps": send_rate_tps, "arguments": dict(arguments or {})}


def smoke_rounds(sweeps, variant):
    """regimes.smoke shape — functional correctness only, never a scalability datapoint."""
    s = sweeps["regimes"]["smoke"]
    tps = s["send_rate_tps"]
    pool = s["cases"] * s["evidence_per_case"]
    payload = sweeps["workload"]["payload_bytes"]
    rounds = [
        _spec("smoke-create", "createEvidence.js", pool, tps, {"payloadBytes": payload}),
        _spec("smoke-logs", "accessLog.js", s["cases"] * s["logs_per_case_max"], tps,
              {"pool": pool, "payloadBytes": payload}),
    ]
    if variant == "standard":
        # Stage-1 gate in miniature: every worker appends to ONE evidence; the
        # (evidenceId, counter) sub-key design must yield zero MVCC conflicts.
        rounds.append(_spec("smoke-access-shared-gate", "accessLog.js", s["cases"] * s["logs_per_case_min"], tps,
                            {"scenario": "shared", "sharedEvidenceId": "ev-shared-gate", "payloadBytes": payload}))
    if variant in ANCHORED_VARIANTS:
        rounds.append(_spec("smoke-verify", "verify.js", s["cases"] * s["logs_per_case_min"], tps,
                            {"seedCount": s["cases"]}))
    return rounds


def ops_rounds(sweeps, variant, cases, send_rate_tps):
    """Per-operation breakdown at one operating point: writes, then reads,
    + verify-event for the anchored variants. txNumber = pool P = evidence_per_case x cases."""
    pool = sweeps["workload"]["evidence_per_case"] * cases
    payload = sweeps["workload"]["payload_bytes"]
    # txNumber is the TOTAL across workers, but `pool`/`seedCount` are PER WORKER
    # (each worker seeds its own disjoint evidence ids). Sizing the per-worker
    # pool at P would seed P x workers items to perform P timed operations —
    # 4x the ledger writes, three quarters of them never touched. Ceiling
    # division gives each worker just what it will use while keeping
    # per_worker x workers >= txNumber, which `dispose` REQUIRES: it disposes
    # each pooled item once and throws when it runs out, so flooring would
    # starve the round whenever P is not divisible by the worker count.
    per_worker = max(1, -(-pool // sweeps["workers"]))
    w = {"pool": per_worker, "payloadBytes": payload}
    rounds = [
        _spec("create", "createEvidence.js", pool, send_rate_tps, {"payloadBytes": payload}),
        _spec("transfer", "transferCustody.js", pool, send_rate_tps, w),
        _spec("access", "accessLog.js", pool, send_rate_tps, w),
        _spec("dispose", "disposeEvidence.js", pool, send_rate_tps, w),
        _spec("read-evidence", "read.js", pool, send_rate_tps, {"fn": "ReadEvidence", "pool": per_worker}),
        _spec("read-trail", "read.js", pool, send_rate_tps, {"fn": "GetAuditTrail", "pool": per_worker}),
    ]
    if variant in ANCHORED_VARIANTS:
        rounds.append(_spec("verify-event", "verify.js", pool, send_rate_tps, {"seedCount": per_worker}))
    return rounds


def trace_round(sweeps, variant, label, trace_path, slice_k, slice_size, send_rate_tps):
    """One replayed trace slice: txNumber is the TOTAL across workers (Caliper splits it)."""
    return _spec(label, "trace.js", slice_size * sweeps["workers"], send_rate_tps,
                 {"trace": os.path.abspath(trace_path), "slice": int(slice_k),
                  "sliceSize": int(slice_size), "variant": variant})


# ---------------------------------------------------------------- rendering

def render_bench(sweeps, variant, name, description, rounds, channels=1, monitor=True):
    """Full Caliper benchconfig dict for a list of round specs."""
    ch = channels_for(variant, channels)
    out_rounds = []
    for r in rounds:
        # `variant` is a COMMON argument, not only a trace-round one: payloads.js
        # caseSelector suppresses the case-NNN spread for standard/anchoring by
        # variant name alone. Without it, `channels: 1` still yields 'case-001',
        # which routes Standard's fabric requests at a channel that does not
        # exist in networks/coc-main.yaml (the connector throws before any tx)
        # and stamps Anchoring's events with a caseId instead of 'shared'.
        args = {"mode": mode_for(variant), "label": r["label"], "channels": ch, "variant": variant}
        args.update(r["arguments"])
        out_rounds.append({
            "label": r["label"],
            "txNumber": r["txNumber"],
            "rateControl": {"type": "fixed-rate", "opts": {"tps": r["sendRateTps"]}},
            "workload": {"module": r["module"], "arguments": args},
        })
    doc = {"test": {"name": name, "description": description,
                    "workers": {"number": sweeps["workers"]}, "rounds": out_rounds}}
    if monitor:
        doc["monitors"] = {"resource": [{"module": "docker", "options": {
            "interval": sweeps["monitor"]["interval_s"],
            "containers": monitor_containers(variant)}}]}
    return doc


def render_round(sweeps, variant, spec, channels=1, monitor=True, name=None, description=None):
    """One-round benchconfig (experiment.py launches one Caliper run per round)."""
    return render_bench(sweeps, variant, name or f"gleipnir-{variant}-{spec['label']}",
                        description or f"{variant}: round {spec['label']} (send rate {spec['sendRateTps']} tx/s)",
                        [spec], channels=channels, monitor=monitor)


def dump_yaml(doc, header_lines=()):
    head = "\n".join([GENERATED, *header_lines])
    return head + "\n" + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True, width=120)


def render_parallel_network(channels):
    blocks = []
    for i in range(1, channels + 1):
        ch = case_name(i)
        # `id` is the real chaincode name on every channel; `contractID` is a
        # per-channel UNIQUE alias — caliper-fabric 0.6.0 keys its contract map
        # by it and aborts on duplicates. The workloads route by channel + id.
        blocks.append(f"  - channelName: {ch}\n    contracts:\n      - id: evidence\n        contractID: evidence-{ch}")
    return "\n".join([
        GENERATED,
        f"# Multi-channel Caliper network config — Parallel variant, {channels}-channel cell.",
        f"name: GLEIPNIR parallel-c{channels}",
        'version: "2.0.0"',
        "",
        "caliper:",
        "  blockchain: fabric",
        "",
        "channels:",
        *blocks,
        "",
        _ORG1_IDENTITY_BLOCK,
    ])
