#!/usr/bin/env python3
"""GLEIPNIR sweep driver (docs/CONTRACTS.md §10, §11; ARCHITECTURE §4.6, §8).

`sweep.py --variant <v> --regime <steady|smoke>` iterates the applicable sweep cells
from benchmark/sweeps.yaml (N for anchoring, K+channels for parallel-anchored, channels
for parallel), repeats each per the N-runs loop, and for each cell: ensures channels,
sets the batcher batch size + a fresh BATCH_EPOCH, seeds the run manifest, checkpoints
storage before/after, runs Caliper, collects, and (anchoring variants, steady regime)
runs the verification-latency benchmark for the same cell (thesis RQ2).

Multi-channel cells (audit F6/F24): the per-cell benchconfig
(benchmarks/steady-<variant>-c<CH>.yaml, generated from sweeps.yaml) spreads each
round's offered load round-robin across ALL provisioned case channels in ONE Caliper
run — never a single "representative" channel. collect.py derives per-channel rates
from the aggregate.

Smoke runIds are prefixed 'smoke-'; steady 'run-'. Smoke uses the smoke-<variant>
benchconfigs generated from regimes.smoke (audit F13) and a single representative
cell — functional correctness only, never mixed with steady-state data.

This orchestrates external tools (docker compose, npx caliper, provision-channel.sh,
checkpoint.py, collect.py); it never generates load itself.
"""
import argparse
import itertools
import json
import os
import subprocess
import sys
import time
from datetime import datetime, timezone

import yaml

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BENCH_DIR = os.path.join(REPO_ROOT, "benchmark")
ORCH = os.path.join(REPO_ROOT, "orchestration")
COMPOSE_DIR = os.path.join(REPO_ROOT, "network", "compose")

VARIANTS = ["standard", "anchoring", "parallel", "parallel-anchored"]
REST_NET = "networks/rest-gateway.yaml"


def load_sweeps():
    with open(os.path.join(BENCH_DIR, "sweeps.yaml"), encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def run(cmd, **kw):
    print("+ " + (cmd if isinstance(cmd, str) else " ".join(cmd)))
    return subprocess.run(cmd, shell=isinstance(cmd, str), cwd=kw.pop("cwd", REPO_ROOT), check=False, **kw)


def set_env_var(key, value):
    """Best-effort update of network/compose/.env (mirrors lib.sh set_env_var)."""
    env_path = os.path.join(COMPOSE_DIR, ".env")
    lines, found = [], False
    if os.path.exists(env_path):
        with open(env_path, encoding="utf-8") as fh:
            lines = fh.read().splitlines()
    for i, ln in enumerate(lines):
        if ln.startswith(key + "="):
            lines[i] = f"{key}={value}"
            found = True
    if not found:
        lines.append(f"{key}={value}")
    with open(env_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")


def recreate_batcher():
    run(["docker", "compose", "-p", "gleipnir", "--project-directory", COMPOSE_DIR,
         "-f", os.path.join(COMPOSE_DIR, "compose-net.yaml"),
         "-f", os.path.join(COMPOSE_DIR, "compose-ca.yaml"),
         "-f", os.path.join(COMPOSE_DIR, "compose-services.yaml"),
         "up", "-d", "--force-recreate", "merkle-batcher"])


def ensure_channels(n):
    for i in range(1, n + 1):
        run([os.path.join(ORCH, "provision-channel.sh"), f"case-{i:03d}"])


def configs_for(variant, regime, cell):
    """Resolve (benchconfig, networkconfig, verify_benchconfig|None) for one cell.

    Every path is generated by benchmark/generate-rounds.js from sweeps.yaml.
    The verify benchconfig (RQ2) applies to the anchoring variants in the steady
    regime only; the smoke-<variant> configs carry their own small verify round.
    """
    ch = cell.get("channels", 1)
    if regime == "smoke":
        bench = f"benchmarks/smoke-{variant}.yaml"
        verify = None
    elif variant == "parallel":
        bench = f"benchmarks/steady-parallel-c{ch}.yaml"
        verify = None
    elif variant == "parallel-anchored":
        bench = f"benchmarks/steady-parallel-anchored-c{ch}.yaml"
        verify = f"benchmarks/steady-verify-c{ch}.yaml"
    elif variant == "anchoring":
        bench = "benchmarks/steady-anchoring.yaml"
        verify = "benchmarks/steady-verify.yaml"
    else:  # standard
        bench = "benchmarks/steady-standard.yaml"
        verify = None

    if variant == "standard":
        net = "networks/coc-main.yaml"
    elif variant == "parallel":
        net = f"networks/parallel-c{ch}.yaml"
    else:  # rest-mode variants (anchoring, parallel-anchored)
        net = REST_NET
    return bench, net, verify


def seed_manifest(run_id, variant, regime, cell, rep, sweeps, phase):
    """Write the §10 experiment-identity fields BEFORE Caliper runs (audit F30).

    collect.py merges into this file (setdefault semantics keep these fields).
    """
    out_dir = os.path.join(BENCH_DIR, "results", run_id)
    os.makedirs(out_dir, exist_ok=True)
    connector = "fabric" if variant in ("standard", "parallel") and phase == "write" else "rest"
    manifest = {
        "runId": run_id,
        "startedAt": datetime.now(timezone.utc).isoformat(),
        "variant": variant,
        "regime": regime,
        "phase": phase,  # write | verify
        "cell": {
            "N": cell.get("N"),
            "K": cell.get("K"),
            "channels": cell.get("channels"),
            "offeredLoadTps": sweeps["offered_load_tps"],
            "repetition": rep,
        },
        "caliper": {"binding": "fabric:fabric-gateway", "version": "0.6.0", "connector": connector},
        "notes": "",
    }
    with open(os.path.join(out_dir, "manifest.json"), "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=2)


def caliper(run_id, benchconfig, networkconfig):
    out_dir = os.path.join(BENCH_DIR, "results", run_id)
    os.makedirs(out_dir, exist_ok=True)
    log_path = os.path.join(out_dir, "caliper.log")
    report_path = os.path.join(out_dir, "report.html")
    cmd = ["npx", "caliper", "launch", "manager",
           "--caliper-workspace", ".",
           "--caliper-benchconfig", benchconfig,
           "--caliper-networkconfig", networkconfig,
           "--caliper-report-path", report_path]
    print("+ (in benchmark/) " + " ".join(cmd) + f"  | tee {log_path}")
    with open(log_path, "w", encoding="utf-8") as log:
        proc = subprocess.Popen(cmd, cwd=BENCH_DIR, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
        for line in proc.stdout:
            sys.stdout.write(line)
            log.write(line)
        proc.wait()
    return report_path


def cells_for(variant, sweeps, regime):
    """Yield cell dicts (N/K/channels) for the variant, excluding the repetition loop.

    Smoke is functional-only: one representative cell per variant (first value of
    each axis), never the full sweep (audit F13).
    """
    if regime == "smoke":
        if variant == "anchoring":
            yield {"N": sweeps["anchoring_batch_N"][0]}
        elif variant == "parallel":
            yield {"channels": 1}
        elif variant == "parallel-anchored":
            yield {"K": sweeps["parallel_anchored_batch_K"][0], "channels": 1}
        else:
            yield {}
        return
    if variant == "standard":
        yield {}
    elif variant == "anchoring":
        for n in sweeps["anchoring_batch_N"]:
            yield {"N": n}
    elif variant == "parallel":
        for ch in sweeps["channel_counts"]:
            yield {"channels": ch}
    elif variant == "parallel-anchored":
        for k, ch in itertools.product(sweeps["parallel_anchored_batch_K"], sweeps["channel_counts"]):
            yield {"K": k, "channels": ch}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--variant", required=True, choices=VARIANTS)
    ap.add_argument("--regime", default="steady", choices=["steady", "smoke"])
    args = ap.parse_args()

    sweeps = load_sweeps()
    reps = sweeps["repetitions"] if args.regime == "steady" else 1
    prefix = "run" if args.regime == "steady" else "smoke"

    for cell in cells_for(args.variant, sweeps, args.regime):
        tag = "-".join([f"{k}{v}" for k, v in cell.items()]) or "base"
        needs_batcher = "N" in cell or "K" in cell
        if "N" in cell:
            set_env_var("BATCH_N", cell["N"])
        if "K" in cell:
            set_env_var("BATCH_K", cell["K"])
        if needs_batcher:
            # Fresh epoch per batcher lifetime: the ledger persists across cells,
            # so batchIds must never repeat a committed (scope,batchId) key
            # (audit F44). Unique even when the same sweep is re-run.
            set_env_var("BATCH_EPOCH", f"{tag}-{int(time.time())}")
            recreate_batcher()
        if "channels" in cell:
            ensure_channels(cell["channels"])

        benchconfig, netcfg, verifycfg = configs_for(args.variant, args.regime, cell)

        for rep in range(reps):
            run_id = f"{prefix}-{args.variant}-{tag}-r{rep}"
            print(f"\n===== cell {run_id} =====")

            seed_manifest(run_id, args.variant, args.regime, cell, rep, sweeps, "write")
            run([sys.executable, os.path.join(ORCH, "checkpoint.py"), run_id, "--label", "t0"])
            caliper(run_id, benchconfig, netcfg)
            run([sys.executable, os.path.join(ORCH, "checkpoint.py"), run_id, "--label", "t1"])
            run([sys.executable, os.path.join(ORCH, "collect.py"), run_id])

            if verifycfg:
                # Verification/audit latency for the SAME cell (thesis RQ2,
                # audit F8) — its own runId so write and verify artifacts never
                # mix; storage checkpoints belong to the write phase only.
                verify_id = f"{run_id}-verify"
                print(f"===== cell {verify_id} (RQ2) =====")
                seed_manifest(verify_id, args.variant, args.regime, cell, rep, sweeps, "verify")
                caliper(verify_id, verifycfg, REST_NET)
                run([sys.executable, os.path.join(ORCH, "collect.py"), verify_id])

    print("\nsweep complete.")


if __name__ == "__main__":
    main()
