#!/usr/bin/env python3
"""GLEIPNIR sweep driver (docs/CONTRACTS.md §10, §11; ARCHITECTURE §4.6, §8).

`sweep.py --variant <v> --regime <steady|smoke>` iterates the applicable sweep cells
from benchmark/sweeps.yaml (N for anchoring, K+channels for parallel-anchored, channels
for parallel), repeats each per the N-runs loop, and for each cell: ensures channels,
sets the batcher batch size + a fresh BATCH_EPOCH, seeds the run manifest, checkpoints
storage before/after, runs Caliper, collects, and (anchoring variants, steady regime)
runs the verification-latency benchmark for the same cell (thesis RQ2).

Multi-channel cells (audit F6/F24): the per-cell benchconfig
(benchmarks/steady-<variant>-c<CH>.yaml, generated from sweeps.yaml) spreads each
round's offered load round-robin across ALL provisioned case channels in ONE Caliper
run — never a single "representative" channel. collect.py derives per-channel rates
from the aggregate.

Smoke runIds are prefixed 'smoke-'; steady 'run-'. Smoke uses the smoke-<variant>
benchconfigs generated from regimes.smoke (audit F13) and a single representative
cell — functional correctness only, never mixed with steady-state data.

This orchestrates external tools (docker compose, npx caliper, provision-channel.sh,
checkpoint.py, collect.py); it never generates load itself.
"""
import argparse
import itertools
import json
import os
import subprocess
import sys
import time
from datetime import datetime, timezone

import yaml

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BENCH_DIR = os.path.join(REPO_ROOT, "benchmark")
ORCH = os.path.join(REPO_ROOT, "orchestration")
COMPOSE_DIR = os.path.join(REPO_ROOT, "network", "compose")

VARIANTS = ["standard", "anchoring", "parallel", "parallel-anchored"]
REST_NET = "networks/rest-gateway.yaml"


def load_sweeps():
    with open(os.path.join(BENCH_DIR, "sweeps.yaml"), encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def run(cmd, check=False, **kw):
    """Run a subprocess. check=True raises on non-zero exit (F76): the sweep's
    provisioning/checkpoint/collect steps MUST fail loudly — a silent non-zero
    there produced empty or missing manifests that only surfaced much later.
    Caliper itself is streamed separately (see caliper()), not through here."""
    print("+ " + (cmd if isinstance(cmd, str) else " ".join(cmd)))
    return subprocess.run(cmd, shell=isinstance(cmd, str), cwd=kw.pop("cwd", REPO_ROOT), check=check, **kw)


def assert_collected(run_id):
    """Fail loudly if collect.py produced a manifest with zero rounds (F48/F76):
    a caliper.log parse miss or a run with no successful rounds must not pass
    silently as a 'done' cell."""
    manifest_path = os.path.join(BENCH_DIR, "results", run_id, "manifest.json")
    with open(manifest_path, encoding="utf-8") as fh:
        manifest = json.load(fh)
    rounds = manifest.get("rounds") or []
    if not rounds:
        raise SystemExit(
            f"FATAL: collect produced 0 rounds for {run_id} — caliper.log parse failed "
            f"or the run had no successful rounds (F76). Inspect "
            f"benchmark/results/{run_id}/caliper.log before continuing.")
    print(f"  collected {len(rounds)} rounds for {run_id}")


def reset_verify_metrics():
    """Truncate the verification service's RQ2 metrics file so a verify run's
    manifest summarises exactly that run's requests (the named volume persists
    across cells). No-op if the container is absent (non-anchoring variants)."""
    subprocess.run(
        ["docker", "exec", "gleipnir-verification", "sh", "-c", ": > /verify-metrics/verify.jsonl"],
        check=False, capture_output=True, text=True)


def set_env_var(key, value):
    """Best-effort update of network/compose/.env (mirrors lib.sh set_env_var)."""
    env_path = os.path.join(COMPOSE_DIR, ".env")
    lines, found = [], False
    if os.path.exists(env_path):
        with open(env_path, encoding="utf-8") as fh:
            lines = fh.read().splitlines()
    for i, ln in enumerate(lines):
        if ln.startswith(key + "="):
            lines[i] = f"{key}={value}"
            found = True
    if not found:
        lines.append(f"{key}={value}")
    with open(env_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")


def recreate_batcher():
    run(["docker", "compose", "-p", "gleipnir", "--project-directory", COMPOSE_DIR,
         "-f", os.path.join(COMPOSE_DIR, "compose-net.yaml"),
         "-f", os.path.join(COMPOSE_DIR, "compose-ca.yaml"),
         "-f", os.path.join(COMPOSE_DIR, "compose-services.yaml"),
         "up", "-d", "--force-recreate", "merkle-batcher"], check=True)


def ensure_channels(n):
    for i in range(1, n + 1):
        run([os.path.join(ORCH, "provision-channel.sh"), f"case-{i:03d}"], check=True)


def configs_for(variant, regime, cell):
    """Resolve (benchconfig, networkconfig, verify_benchconfig|None) for one cell.

    Every path is generated by benchmark/generate-rounds.js from sweeps.yaml.
    The verify benchconfig (RQ2) applies to the anchoring variants in the steady
    regime only; the smoke-<variant> configs carry their own small verify round.
    """
    ch = cell.get("channels", 1)
    if regime == "smoke":
        bench = f"benchmarks/smoke-{variant}.yaml"
        verify = None
    elif variant == "parallel":
        bench = f"benchmarks/steady-parallel-c{ch}.yaml"
        verify = None
    elif variant == "parallel-anchored":
        bench = f"benchmarks/steady-parallel-anchored-c{ch}.yaml"
        verify = f"benchmarks/steady-verify-c{ch}.yaml"
    elif variant == "anchoring":
        bench = "benchmarks/steady-anchoring.yaml"
        verify = "benchmarks/steady-verify.yaml"
    else:  # standard
        bench = "benchmarks/steady-standard.yaml"
        verify = None

    if variant == "standard":
        net = "networks/coc-main.yaml"
    elif variant == "parallel":
        net = f"networks/parallel-c{ch}.yaml"
    else:  # rest-mode variants (anchoring, parallel-anchored)
        net = REST_NET
    return bench, net, verify


def seed_manifest(run_id, variant, regime, cell, rep, sweeps, phase):
    """Write the §10 experiment-identity fields BEFORE Caliper runs (audit F30).

    collect.py merges into this file (setdefault semantics keep these fields).
    """
    out_dir = os.path.join(BENCH_DIR, "results", run_id)
    os.makedirs(out_dir, exist_ok=True)
    connector = "fabric" if variant in ("standard", "parallel") and phase == "write" else "rest"
    manifest = {
        "runId": run_id,
        "startedAt": datetime.now(timezone.utc).isoformat(),
        "variant": variant,
        "regime": regime,
        "phase": phase,  # write | verify
        "cell": {
            "N": cell.get("N"),
            "K": cell.get("K"),
            "channels": cell.get("channels"),
            "offeredLoadTps": sweeps["offered_load_tps"],
            "repetition": rep,
        },
        "caliper": {"binding": "fabric:fabric-gateway", "version": "0.6.0", "connector": connector},
        "notes": "",
    }
    with open(os.path.join(out_dir, "manifest.json"), "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=2)


def caliper(run_id, benchconfig, networkconfig):
    out_dir = os.path.join(BENCH_DIR, "results", run_id)
    os.makedirs(out_dir, exist_ok=True)
    log_path = os.path.join(out_dir, "caliper.log")
    report_path = os.path.join(out_dir, "report.html")
    cmd = ["npx", "caliper", "launch", "manager",
           "--caliper-workspace", ".",
           "--caliper-benchconfig", benchconfig,
           "--caliper-networkconfig", networkconfig,
           "--caliper-report-path", report_path]
    print("+ (in benchmark/) " + " ".join(cmd) + f"  | tee {log_path}")
    with open(log_path, "w", encoding="utf-8") as log:
        proc = subprocess.Popen(cmd, cwd=BENCH_DIR, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
        for line in proc.stdout:
            sys.stdout.write(line)
            log.write(line)
        proc.wait()
    return report_path


def cells_for(variant, sweeps, regime):
    """Yield cell dicts (N/K/channels) for the variant, excluding the repetition loop.

    Smoke is functional-only: one representative cell per variant (first value of
    each axis), never the full sweep (audit F13).
    """
    if regime == "smoke":
        if variant == "anchoring":
            yield {"N": sweeps["anchoring_batch_N"][0]}
        elif variant == "parallel":
            yield {"channels": 1}
        elif variant == "parallel-anchored":
            yield {"K": sweeps["parallel_anchored_batch_K"][0], "channels": 1}
        else:
            yield {}
        return
    if variant == "standard":
        yield {}
    elif variant == "anchoring":
        for n in sweeps["anchoring_batch_N"]:
            yield {"N": n}
    elif variant == "parallel":
        for ch in sweeps["channel_counts"]:
            yield {"channels": ch}
    elif variant == "parallel-anchored":
        for k, ch in itertools.product(sweeps["parallel_anchored_batch_K"], sweeps["channel_counts"]):
            yield {"K": k, "channels": ch}


def _load_manifest(run_id):
    path = os.path.join(BENCH_DIR, "results", run_id, "manifest.json")
    if not os.path.exists(path):
        return None
    try:
        with open(path, encoding="utf-8") as fh:
            return json.load(fh)
    except (json.JSONDecodeError, OSError):
        return None


def write_collected(run_id):
    """A write run is complete iff its manifest has parsed rounds AND storage —
    i.e. collect.py ran to completion (a crash mid-run leaves a seeded manifest
    with neither)."""
    m = _load_manifest(run_id)
    return bool(m and (m.get("rounds") or []) and m.get("storage")
                and m["storage"].get("bytesPerEventBlockstore") is not None)


def verify_collected(verify_id):
    m = _load_manifest(verify_id)
    vs = m.get("verifySteps") if m else None
    return bool(vs and vs.get("count", 0) > 0)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--variant", required=True, choices=VARIANTS)
    ap.add_argument("--regime", default="steady", choices=["steady", "smoke"])
    ap.add_argument("--resume", action="store_true",
                    help="skip cells/reps already fully collected (idempotent restart "
                         "after a crash); only the missing runs execute")
    args = ap.parse_args()

    sweeps = load_sweeps()
    reps = sweeps["repetitions"] if args.regime == "steady" else 1
    prefix = "run" if args.regime == "steady" else "smoke"

    for cell in cells_for(args.variant, sweeps, args.regime):
        tag = "-".join([f"{k}{v}" for k, v in cell.items()]) or "base"
        benchconfig, netcfg, verifycfg = configs_for(args.variant, args.regime, cell)
        run_ids = [f"{prefix}-{args.variant}-{tag}-r{rep}" for rep in range(reps)]

        # --resume: if EVERY rep of this cell is already collected, skip the whole
        # cell — no batcher recreate, no channel provision (F44 epoch untouched).
        if args.resume and all(
            write_collected(rid) and (verify_collected(f"{rid}-verify") if verifycfg else True)
            for rid in run_ids
        ):
            print(f"[resume] cell {tag}: all {reps} rep(s) already collected — skipping")
            continue

        needs_batcher = "N" in cell or "K" in cell
        if "N" in cell:
            set_env_var("BATCH_N", cell["N"])
        if "K" in cell:
            set_env_var("BATCH_K", cell["K"])
        if needs_batcher:
            # Fresh epoch per batcher lifetime: the ledger persists across cells,
            # so batchIds must never repeat a committed (scope,batchId) key
            # (audit F44). Unique even when the same sweep is re-run.
            set_env_var("BATCH_EPOCH", f"{tag}-{int(time.time())}")
            recreate_batcher()
        if "channels" in cell:
            ensure_channels(cell["channels"])

        for rep in range(reps):
            run_id = run_ids[rep]

            if args.resume and write_collected(run_id):
                print(f"[resume] {run_id}: write already collected — skipping")
            else:
                print(f"\n===== cell {run_id} =====")
                seed_manifest(run_id, args.variant, args.regime, cell, rep, sweeps, "write")
                run([sys.executable, os.path.join(ORCH, "checkpoint.py"), run_id, "--label", "t0"], check=True)
                caliper(run_id, benchconfig, netcfg)
                run([sys.executable, os.path.join(ORCH, "checkpoint.py"), run_id, "--label", "t1"], check=True)
                run([sys.executable, os.path.join(ORCH, "collect.py"), run_id], check=True)
                assert_collected(run_id)

            if verifycfg:
                # Verification/audit latency for the SAME cell (thesis RQ2,
                # audit F8) — its own runId so write and verify artifacts never
                # mix; storage checkpoints belong to the write phase only.
                verify_id = f"{run_id}-verify"
                if args.resume and verify_collected(verify_id):
                    print(f"[resume] {verify_id}: already collected — skipping")
                    continue
                print(f"===== cell {verify_id} (RQ2) =====")
                seed_manifest(verify_id, args.variant, args.regime, cell, rep, sweeps, "verify")
                # Reset the per-request step log so the verify manifest summarises
                # exactly this run (the named volume persists across cells).
                reset_verify_metrics()
                caliper(verify_id, verifycfg, REST_NET)
                run([sys.executable, os.path.join(ORCH, "collect.py"), verify_id], check=True)
                assert_collected(verify_id)

    print("\nsweep complete.")


if __name__ == "__main__":
    main()
